version: '3.9'

services:
  zookeeper:
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
      - my_network
  kafka:
    image: debezium/kafka:latest
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - my_network
  postgres:
    image: debezium/postgres:latest
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgresuser
     - POSTGRES_PASSWORD=postgrespw
     - POSTGRES_DB=inventory
    networks:
      - my_network
  connect:
      image: debezium/connect
      ports:
      - 8083:8083
      links:
      - zookeeper
      - kafka
      - postgres
      environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses
      networks:
      - my_network

networks:
  my_network:
    driver: bridge
    external: true
    internal: true


